package it.polimi.se2019.limperio.nicotera.italia.events.events_by_server;

import it.polimi.se2019.limperio.nicotera.italia.model.*;

import java.io.Serializable;
import java.util.ArrayList;


/**
 * Event generated by some components located in server side.
 * <p>
 *     Represents a kind of general event and is usually adapted to the different
 *     situations according to the values of the different boolean attributes.
 * </p>
 * <p>
 *     The way to understand, by the client, which wind of Event was sent by Server is evaluated
 *     the state of the relative boolean attribute.
 *     Example: if an event is the type of MapEvent, all the boolean attributes will be false apart
 *     isMapEvent.
 *
 * </p>
 * @author Pietro L'Imperio
 */
public class ServerEvent implements Serializable {
    /**
     * The message stored in the event.
     */
    private String message;
    /**
     * The list of nickname interested to receive the event.
     */
    private ArrayList<String> nicknames = new ArrayList<>();
    /**
     * The player board updated in {@link PlayerBoardEvent}
     */
    private PlayerBoard playerBoard = null;
    /**
     * The map (only the matrix) updated in {@link MapEvent}
     */
    private Square[][] map = null;
    /**
     * The killshot track updated in {@link KillshotTrackEvent}
     */
    private KillShotTrack killShotTrack = null;
    /**
     * The list of powerUp cards in alias-mode to send to clients in some kind of events like {@link RequestDiscardPowerUpCardEvent}
     */
    private ArrayList<AliasCard> powerUpCards = null;

    private boolean isPlayerBoardEvent = false;
    private boolean isMapEvent = false;
    private boolean isKillshotTrackEvent = false;
    private boolean isRequestForDiscardPowerUpCardEvent = false;
    private boolean isDiscardPowerUpCardToSpawnEvent = false;
    private boolean isFirstActionOfTurnEvent = false;
    private boolean isSelectionSquareForSquareWhereCatch = false;

    public boolean isSelectionSquareForSquareWhereCatch() {
        return isSelectionSquareForSquareWhereCatch;
    }

    public void setSelectionSquareForSquareWhereCatch(boolean selectionSquareForSquareWhereCatch) {
        isSelectionSquareForSquareWhereCatch = selectionSquareForSquareWhereCatch;
    }

    public boolean isFirstActionOfTurnEvent() {
        return isFirstActionOfTurnEvent;
    }

    public void setFirstActionOfTurnEvent(boolean firstActionOfTurnEvent) {
        isFirstActionOfTurnEvent = firstActionOfTurnEvent;
    }

    public ArrayList<AliasCard> getPowerUpCards() {
        return powerUpCards;
    }

    public void setPowerUpCards(ArrayList<AliasCard> powerUpCards) {
        this.powerUpCards = powerUpCards;
    }

    public ServerEvent(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }


    public void setNickname(ArrayList<String> nicknames) {
        this.nicknames = nicknames;
    }

    public ArrayList<String> getNicknames() {
        return nicknames;
    }

    public PlayerBoard getPlayerBoard() {
        return playerBoard;
    }

    public void setPlayerBoard(PlayerBoard playerBoard) {
        this.playerBoard = playerBoard;
    }

    public boolean isPlayerBoardEvent() {
        return isPlayerBoardEvent;
    }

    public void setPlayerBoardEvent(boolean playerBoardEvent) {
        isPlayerBoardEvent = playerBoardEvent;
    }

    public boolean isMapEvent() {
        return isMapEvent;
    }

    public void setMapEvent(boolean mapEvent) {
        isMapEvent = mapEvent;
    }

    public Square[][] getMap() {
        return map;
    }

    public void setMap(Square[][] map) {
        this.map = map;
    }

    public KillShotTrack getKillShotTrack() {
        return killShotTrack;
    }

    public void setKillShotTrack(KillShotTrack killShotTrack) {
        this.killShotTrack = killShotTrack;
    }

    public boolean isKillshotTrackEvent() {
        return isKillshotTrackEvent;
    }

    public void setKillshotTrackEvent(boolean killshotTrackEvent) {
        isKillshotTrackEvent = killshotTrackEvent;
    }


    public boolean isRequestForDiscardPowerUpCardEvent() {
        return isRequestForDiscardPowerUpCardEvent;
    }

    public void setRequestForDiscardPowerUpCardEvent(boolean drawTwoPowerUpCard) {
        isRequestForDiscardPowerUpCardEvent = drawTwoPowerUpCard;
    }

    public boolean isDiscardPowerUpCardToSpawnEvent() {
        return isDiscardPowerUpCardToSpawnEvent;
    }

    public void setDiscardPowerUpCardToSpawnEvent(boolean discardPowerUpCardToSpawnEvent) {
        isDiscardPowerUpCardToSpawnEvent = discardPowerUpCardToSpawnEvent;
    }

    /**
     * Represents a simplified structure to encapsulate the main attributes of cards
     * (Weapon and PowerUp) to send them to clients removing from them the possibility to use
     * directly their effects.
     *
     */

    public static class AliasCard implements Serializable{
        /**
         * The name of card
         */
        String name;
        /**
         * The description of card
         */
        String description;
        /**
         * The color of card
         */
        ColorOfCard_Ammo color;

        public AliasCard(String name, String description, ColorOfCard_Ammo color) {
            this.name = name;
            this.description = description;
            this.color = color;
        }

        public String getName() {
            return name;
        }

        public String getDescription() {
            return description;
        }

        public ColorOfCard_Ammo getColor() {
            return color;
        }
    }


}
